application: evenge-2014
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: index.application
  
-   url: /_dt/css
    static_dir: css

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest