application: evenge-2014
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_dt/css
  static_dir: _dt/css

- url: /_dt/img
  static_dir: _dt/img

- url: /listarAsistentes
  script: _oo.class.asistente.application

- url: /listarEventos
  script: _oo.class.evento.application

- url: /listarPonentes
  script: _oo.class.ponente.application

- url: /listarOrganizaciones
  script: _oo.class.organizacion.application

- url: /asistente
  script: _oo.class.asistente.application

- url: /organizacion
  script: _oo.class.organizacion.application

- url: /evento
  script: _oo.class.evento.application

- url: /usuario
  script: _oo.class.usuario.application

- url: /ponente
  script: _oo.class.ponente.application

- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
