application: evenge-2014
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_dt/css
  static_dir: _dt/css

- url: /asistente
  script: _oo.class.asistente.application

<<<<<<< HEAD
- url: /organizacion
  script: _oo.class.organizacion.application

- url: /ponente
  script: _oo.class.ponente.application
=======
- url: /evento
  script: _oo.class.evento.application
>>>>>>> master

- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
